# Put a copy of / link to this file in the binary's directory: e.g. target/debug/deps
# Then modify the patterns below as desired.

[appenders.async_console]
kind = "async_console"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}\n"
# pattern = "{l} [{M} #FS#{f}#FE#:{L}] {m}\n"

[[appenders.async_console.filter]]
kind = "threshold"
level = "info"

[appenders.async_file]
kind = "async_file"
output_file_name = "Node.log"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}\n"
append = false

[root]
level = "error"
appenders = ["async_console", "async_file"]

[loggers."crust"]
level = "debug"
appenders = ["async_file"]
additive = false

[loggers."routing"]
level = "debug"

[loggers."safe_vault"]
level = "debug"

